# Generated by Django 2.1.2 on 2018-10-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('shell', models.CharField(max_length=200)),
                ('base_layer', models.CharField(max_length=2000)),
                ('mixin', models.CharField(max_length=2000)),
                ('condiment', models.CharField(max_length=2000)),
                ('seasoning', models.CharField(max_length=2000)),
            ],
        ),
    ]
