# Generated by Django 2.1.2 on 2018-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taquito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
